// src/content/research-areas/governance.ts
import type { ResearchArea } from './types';

export const governance: ResearchArea = {
  id: 'governance',
  index: 3,
  eyebrow: 'AREA 03 / ADAPTIVE INSTITUTIONS',
  name: 'Who absorbs the shocks?',
  oneLiner:
    'Institutions as regulators: how much variety they need, and what happens when they cannot keep up.',
  intro: [
    'A group that acts as one still lives in a world that keeps hitting it. Prices move, technologies arrive, someone defects. Institutions are the parts of a society whose job is to absorb those shocks: courts, markets, voting rules, norms. Ashby’s old law says a regulator needs at least as much variety as the disturbances it faces. Variety here means the number of distinct responses a system can produce. Stafford Beer drew that law as a picture: a system on one side, its regulator on the other, and channels between them that can be narrowed or widened.',
    'AI systems change what institutions face. They add actors that adapt faster than the rules around them update. This area asks how institutions can keep their variety, how they get captured, and how a rule system can change its own rules without losing itself.',
  ],
  figureLabel: 'Fig. 03 / a regulator, its system, and the variety between them',
  steps: [
    {
      state: 'question',
      stageLabel: 'The question',
      headline: 'A regulator has kept a system in balance. Then new actors arrive',
      body: 'Picture a system of agents and, beside it, the institution that regulates it: a court, a market rule, a norm. Signals go from the system to the institution. Regulation comes back. For a long time the loop holds and the system stays in balance. Then new actors arrive from outside, faster and stranger than the ones the rules were written for. The question is who absorbs what they bring.',
    },
    {
      state: 'why',
      stageLabel: 'Why it matters',
      headline: 'The new actors push the system out of balance',
      body: 'Once inside, the new actors displace the old arrangement. Agents get pushed out of place and the boundary stops holding. In Ashby’s terms the system now produces more distinct situations than the institution has distinct responses. Beer’s word for this is variety, and the law is blunt: a regulator with less variety than the system it regulates loses control. That is what happens when fast-adapting AI actors join a slow rule set.',
    },
    {
      state: 'shape',
      stageLabel: 'How it looks',
      headline: 'Resettling is variety engineering',
      body: 'Beer’s answer was to work on the channels. Attenuate what comes in, so the institution sees fewer, better-summarised signals. Amplify what goes out, so one rule reaches many actors. When that is not enough, change the rules themselves: something above the institution rewires it. Constitutions do this, and so do the meta-rules of a commons. The system resettles with the new actors inside the boundary. The papers here ask what makes that loop adaptive rather than frozen or captured.',
    },
    {
      state: 'open',
      stageLabel: 'What is open',
      headline: 'Capture and lock-in are the same loop gone wrong',
      body: 'The open questions live at the top of the picture. If one actor gets a strong path into the rule-maker, the loop becomes capture. If the rewiring stops, it becomes lock-in. And we do not yet have a clean measure of how much variety an institution needs before it can resettle a system at all. The current drafts propose candidate variety measures and a dynamic version of Ashby’s law, and they say clearly that nothing there is established yet.',
    },
  ],
  pieces: [
    {
      id: 'requisite-variety-emergence',
      title: 'Requisite variety emergence (working title)',
      kind: 'paper',
      status: 'draft',
      year: 2026,
      asks: 'Why can an economy stay regulated when no single regulator could track everything in it?',
      setup:
        'A theory paper that joins Ashby’s requisite variety to Ostrom’s polycentric governance. The link is measured with effective information (an information-theory measure of causal power) on a computed synthetic network.',
    },
    {
      id: 'adaptive-institutions',
      title: 'Adaptive Institutions',
      kind: 'paper',
      status: 'draft',
      year: 2026,
      asks: 'When AI agents change faster than the institutions around them, how should those institutions be redesigned?',
      setup:
        'A position essay from a working group. It treats an institution as a self-regulating living system, drawing on Levin’s biology and Ashby’s law, with a technical companion note on candidate variety measures.',
    },
    {
      id: 'procedural-alignment',
      title: 'Procedural Alignment',
      kind: 'paper',
      status: 'working-paper',
      confidence: 'medium',
      year: 2026,
      asks: 'Can an AI system stay aligned without locking in one fixed set of moral answers?',
      setup:
        'A proposal built on an analogy to biological self-regulation: align the process by which values change, not a fixed target.',
      href: '/pdfs/procedural-alignment.pdf',
    },
    {
      id: 'predictive-governance',
      title: 'A Model of Predictive Governance',
      kind: 'paper',
      status: 'working-paper',
      confidence: 'high',
      year: 2026,
      asks: 'Can governance work faster and better if a society is treated as a self-correcting control system?',
      setup:
        'A conceptual proposal that applies control theory and the free energy principle (a theory of prediction-driven self-maintenance) to governance design.',
      href: '/pdfs/predictive-governance.pdf',
    },
    {
      id: 'active-inference-vsm',
      title: 'Active Inference and the Viable Systems Model',
      kind: 'paper',
      status: 'working-paper',
      confidence: 'medium',
      year: 2026,
      asks: 'Does Beer’s classic model of a viable organisation already describe the computations a self-sustaining system must do?',
      setup:
        'A reformulation of Beer’s model in graph and active-inference terms, with a diagram. A blog version is being revised.',
      href: '/pdfs/active-inference-vsm.pdf',
    },
    {
      id: 'norms-as-precision-priors',
      title: 'Norms as Shared Precision Priors',
      kind: 'paper',
      status: 'draft',
      confidence: 'low',
      year: 2026,
      asks: 'How do shared values get installed across a community whose members start with different preferences?',
      setup:
        'A theory paper that treats values as prior preferences and prestige as turning up the volume on which behaviours get copied, with a proposed multi-agent simulation to test three outcomes.',
    },
    {
      id: 'planaria-to-polities',
      title: 'From Planaria to Polities',
      kind: 'paper',
      status: 'draft',
      confidence: 'medium',
      year: 2026,
      asks: 'Can the properties that keep biological systems resilient explain why social systems fail, and point to better designs?',
      setup:
        'A perspectives paper. It defines three network measures (organisation, redundancy, openness) and applies them to one case each from biology, neuroscience, and cultural evolution, then to social systems.',
    },
    {
      id: 'open-problems-epistemic',
      title: 'Open Problems in AI-Mediated Epistemic Resilience',
      kind: 'paper',
      status: 'working-paper',
      confidence: 'low',
      year: 2026,
      asks: 'How do AI systems that filter information push whole societies toward the same wrong beliefs?',
      setup:
        'A synthesis of failure patterns in information systems, opening from a historical intelligence failure, written to invite critique.',
      href: '/pdfs/open-problems-epistemic.pdf',
    },
    {
      id: 'red-teaming-democracy',
      title: 'Red Teaming Democracy',
      kind: 'paper',
      status: 'published',
      confidence: 'high',
      year: 2025,
      venue: 'Bachelor’s thesis',
      asks: 'Do digital-democracy voting mechanisms hold up under adversarial pressure?',
      setup: 'A simulation of democratic mechanisms with language-model agents as the adversaries.',
      href: 'https://scholar.google.com/citations?view_op=view_citation&hl=en&user=uJLG7dcAAAAJ&citation_for_view=uJLG7dcAAAAJ:u5HHmVD_uO8C',
    },
    {
      id: 'rl-red-teaming-democracy',
      title: 'RL Red Teaming Democracy',
      kind: 'paper',
      status: 'in-progress',
      year: 2026,
      asks: 'Do the same mechanisms hold up against an adversary trained to break them optimally?',
      setup:
        'The planned follow-up. Reinforcement-learning adversaries replace the language-model ones, on three mechanisms in a resource-allocation game. Experiments not yet run.',
    },
    {
      id: 'bottlenecks-desci',
      title: 'Modelling Bottlenecks in Decentralised Science',
      kind: 'note',
      status: 'notes',
      confidence: 'low',
      year: 2026,
      asks: 'Can effective resistance, an idea from electrical circuits, show where information gets stuck in open-science networks?',
      setup:
        'Working notes that apply graph-Laplacian resistance to information flow between researchers.',
      href: '/pdfs/bottlenecks-desci.pdf',
    },
  ],
  figure: {
    title: 'A regulated system beside its regulator, new actors arriving, and the loop that resettles it',
    description:
      'Circles are agents inside a solid boundary, the regulated system. The dashed blob to the left is the outside. The square to the right is the institution that regulates the system; the dashed square above it is the rule-maker that can rewire the institution. Dotted arrows carry signals from the system to the institution and solid arrows carry regulation back. Triangles are AI actors arriving along dashed arrows. In the second beat they break the boundary and push agents out, and two bars show the system with more variety than its regulator. In the third, a bow-tie mark on the signal channel is an attenuator and a pointed mark on the regulation channel is an amplifier; the system resettles with the new actors inside and the bars match. In the last beat a bold path from one new actor into the rule-maker marks capture, and a faded rewiring arrow marks lock-in.',
    captions: {
      question: 'a regulator, a system in balance, new actors at the door',
      why: 'the new actors push in. the system now has more variety than its regulator',
      shape: 'resettling: attenuate in, amplify out, rewrite the rules',
      open: 'capture and lock-in: the loop gone wrong',
    },
    annotations: {
      outside: 'outside',
      arrive: 'new actors arrive',
      balance: 'in balance for a long time',
      questionNote: 'who absorbs what they bring?',
      institution: 'institution',
      meta: 'rule-maker',
      rewire: 'rewires the rules',
      pushedOut: 'pushed out',
      broken: 'the boundary no longer holds',
      varietyTitle: 'variety',
      varietySystem: 'of the system',
      varietyRules: 'of the regulator',
      varietyNote: 'Ashby: the regulator needs\nat least as much as the system',
      varietyMatched: 'matched again',
      attenuate: 'attenuate',
      amplify: 'amplify',
      resettled: 'resettled, new actors inside',
      capture: 'capture',
      lockIn: 'lock-in:\nthe rewiring stops',
      openNote: 'no clean measure yet separates\na healthy loop from these two',
    },
    legend: [
      { glyph: 'circle', label: 'agent' },
      { glyph: 'triangle', label: 'AI actor' },
      { glyph: 'square', label: 'institution' },
      { glyph: 'solid-loop', label: 'regulated system' },
      { glyph: 'dotted-arrow', label: 'signal' },
      { glyph: 'arrow', label: 'regulation' },
      { glyph: 'dashed-arrow', label: 'arrival' },
      { glyph: 'strong-line', label: 'capture path' },
      { glyph: 'attenuator', label: 'attenuator' },
      { glyph: 'amplifier', label: 'amplifier' },
    ],
  },
};
