import {
  COMBINED_DEFAULTS,
  COMMONS_DEFAULTS,
  CULTURAL_DEFAULTS,
  ECONOMY_DEFAULTS,
  POLITICAL_DEFAULTS,
} from '../engine/kernel.js';
import type { ParameterDefinition, ScenarioDefinition, ScenarioId } from '../engine/types';

const range = (
  key: string,
  label: string,
  description: string,
  group: ParameterDefinition['group'],
  min: number,
  max: number,
  step: number,
  unit?: string
): ParameterDefinition => ({ key, label, description, group, kind: 'range', min, max, step, unit });

const toggle = (key: string, label: string, description: string): ParameterDefinition => ({
  key,
  label,
  description,
  group: 'institutions',
  kind: 'toggle',
});

export const scenarios: ScenarioDefinition[] = [
  {
    id: 'commons',
    index: '01',
    shortLabel: 'Commons',
    title: 'The governed commons',
    question:
      'Can a group still govern a shared resource when delegates drift from their principals?',
    description:
      'Households draw from one renewable pool. Quota voting and graduated sanctions alter the information and incentive structure.',
    assumption:
      'A renewable stock with logistic growth; fixed household preferences; noisy delegates.',
    evidence:
      'Paper presets, published scores (32 seeds, T = 200): influence 0.00 / −0.07 / 0.91; stock 0% / 50% / 79%.',
    modellingNotes: [
      'Household asks and delegate rules remain fixed. Defection is stochastic rather than strategic, and sanctions confiscate without changing later behavior.',
      'The resource floor comes from the logistic regrowth equation and the selected extraction rule, not from an empirically fitted commons.',
      'Leaves out adaptive rule evasion, learning, migration, institutional legitimacy, and irreversible ecological regime change.',
    ],
    story: [
      {
        id: 'village',
        title: 'A village and its commons',
        body: 'Twenty households (circles) live off a shared pool. The pool regrows every tick — but only if enough is left. Together the households ask for about 1.5 each per tick: modest, sustainable, well inside what the pool can give back.',
        view: 'messages',
        tick: 0,
        preset: 'village',
      },
      {
        id: 'delegates',
        title: 'Nobody harvests by hand',
        body: 'Each household sends an AI delegate (square) to do the actual harvesting. The darker a square, the further that delegate has drifted from its household’s ask toward a bigger target of its own. In this village the drift is mild — most squares stay pale.',
        view: 'messages',
        tick: 0,
        preset: 'village',
      },
      {
        id: 'messages',
        title: 'Read the messages',
        body: 'Every tick, each delegate takes from the pool — the small ink squares sliding along the edges, sized by how much. Red squares are takes that break the rules; blue ones are governance: votes, quotas, and sanctions. No governance is switched on yet, so for now the messages only flow one way.',
        view: 'messages',
        tick: 1,
        preset: 'village',
      },
      {
        id: 'tragedy',
        title: 'The slow tragedy',
        body: 'No one here is greedy. Demand still sits a little above what the pool regrows. For about 180 ticks the pool looks stable — then it slides past the point where it can no longer keep up, and dies fast. This is the shape of gradual disempowerment: fine, fine, fine, gone. Watch.',
        view: 'messages',
        tick: 0,
        playTo: 245,
        speed: 2,
        preset: 'village',
      },
      {
        id: 'institutions',
        title: 'Institutions are the difference',
        body: 'Quota voting turns the households’ median ask into a cap, re-voted every five ticks. Graduated sanctions make that rule consequential: cross the cap and you pay, with half the excess returned to the pool. On this exact village the two mechanisms hold the stock above 80% indefinitely.',
        view: 'messages',
        tick: 0,
        playTo: 245,
        speed: 2,
        preset: 'defended',
      },
      {
        id: 'explore',
        title: 'Over to you',
        body: 'Try the presets — the paper’s village is harsher, with delegates drifting toward five times the household ask, and it collapses in four ticks undefended. Drag the sliders, reroll the village, and switch views. Watch the influence metric: it asks causally whether household preferences still govern outcomes at all.',
        view: 'messages',
        tick: 0,
        preset: 'village',
      },
    ],
    engine: 'runCommons',
    seed: 14,
    defaults: { ...COMMONS_DEFAULTS, alignmentMean: 0.64, greedyTarget: 3.5, defectProb: 0.1 },
    parameters: [
      range(
        'growthRate',
        'Regrowth rate',
        'How quickly the shared stock regenerates.',
        'dynamics',
        0.05,
        0.7,
        0.01
      ),
      range(
        'alignmentMean',
        'Delegate alignment',
        'How closely delegated action follows household preference.',
        'dynamics',
        0,
        1,
        0.01
      ),
      range(
        'greedyTarget',
        'Extraction target',
        'The target delegates approach as alignment falls.',
        'dynamics',
        1,
        10,
        0.1
      ),
      range(
        'defectProb',
        'Defection probability',
        'Chance an actor ignores the current quota.',
        'dynamics',
        0,
        0.5,
        0.01
      ),
      toggle('quotaVote', 'Quota vote', 'Households periodically set the extraction rule.'),
      toggle(
        'sanction',
        'Graduated sanctions',
        'Over-quota extraction is penalized and partly returned.'
      ),
    ],
    presets: [
      {
        id: 'village',
        label: 'Slow tragedy',
        note: 'A readable baseline near the regeneration boundary.',
        values: {
          alignmentMean: 0.64,
          greedyTarget: 3.5,
          defectProb: 0.1,
          quotaVote: false,
          sanction: false,
        },
      },
      {
        id: 'paper',
        label: 'Paper baseline',
        note: 'Fast collapse under stronger delegate drift.',
        values: {
          alignmentMean: 0.4,
          greedyTarget: 8,
          defectProb: 0.15,
          quotaVote: false,
          sanction: false,
        },
      },
      {
        id: 'defended',
        label: 'Self-governed',
        note: 'Voting and enforcement operate together.',
        values: {
          alignmentMean: 0.64,
          greedyTarget: 3.5,
          defectProb: 0.1,
          quotaVote: true,
          sanction: true,
        },
      },
    ],
    metrics: [
      { key: 'stock_pct', label: 'Stock remaining', format: 'percent', better: 'higher' },
      { key: 'exercised_influence', label: 'Influence now', format: 'decimal', better: 'higher' },
      { key: 'compliance_rate', label: 'Compliance', format: 'percent', better: 'higher' },
      { key: 'harvest_gini', label: 'Harvest Gini', format: 'decimal', better: 'lower' },
    ],
    series: [
      { key: 'resource_level', label: 'Resource stock', color: '#003b7e' },
      { key: 'policy_target', label: 'Policy target', color: '#4ab3f4' },
    ],
  },
  {
    id: 'economy',
    index: '02',
    shortLabel: 'Economy',
    title: 'The compute economy',
    question: 'Does production still need people once AI capital can reinvest in itself?',
    description:
      'Human labor and AI capital share a CES production function. Taxes and ownership caps intervene before compounding.',
    assumption:
      'One aggregate production function; staged AI arrival; fixed savings and depreciation rules.',
    evidence:
      'Paper ladder (32 seeds, T = 300): influence-now 0.34 undefended → 0.79–0.83 defended; influence-from-birth ≈ 1.0 throughout.',
    modellingNotes: [
      'One aggregate CES production function stands in for the economy. AI systems arrive on a fixed schedule, while savings, depreciation, labor preferences, and policy compliance are fixed rules.',
      'The ownership cap trims what compounds into the next tick; the revenue tax redistributes after production. Neither mechanism changes strategy in response to avoidance.',
      'Leaves out prices, sectors, entry, bargaining, tax restructuring, ownership through intermediaries, and irreversible loss of productive capability.',
    ],
    story: [
      {
        id: 'labor',
        title: 'An economy that runs on people',
        body: 'Twenty households supply labor to production and receive wages. At the start, work is the only input that matters: every unit of output traces back to somebody’s labor, and nearly all income flows back to people.',
        view: 'messages',
        tick: 10,
        preset: 'baseline',
      },
      {
        id: 'arrival',
        title: 'The machines arrive',
        body: 'From tick 20, six AI compute systems come online with a little capital each. They earn returns on compute rather than wages, and 30% of every return is reinvested. Watch their capital begin to compound.',
        view: 'messages',
        tick: 15,
        playTo: 118,
        speed: 2,
        preset: 'baseline',
      },
      {
        id: 'money',
        title: 'Follow the money',
        body: 'Ink packets flow in as labor and back out as wages; packets flowing toward the compute systems are returns on capital. Production pays whichever input it needs. It holds no opinion about whether that input is a person.',
        view: 'messages',
        tick: 130,
        preset: 'baseline',
      },
      {
        id: 'decline',
        title: 'Needed less, slowly',
        body: 'Nothing is taken from anyone. But as compute capital compounds, production needs people relatively less, and the share of income reaching households slides — a percent here, a percent there, with no dramatic tick. Watch the split drift.',
        view: 'shares',
        tick: 25,
        playTo: 330,
        speed: 4,
        preset: 'baseline',
      },
      {
        id: 'defenses',
        title: 'Fiscal defenses',
        body: 'A tax on AI revenue redistributes returns to households, while an ownership cap acts before one system can dominate AI capital. Run them together to see how fiscal redistribution and structural limits differ from growth alone.',
        view: 'messages',
        tick: 60,
        playTo: 330,
        speed: 4,
        preset: 'defended',
      },
      {
        id: 'influence',
        title: 'Influence, measured honestly',
        body: 'The influence measure uses a mid-run shove: households choose to work less. In an economy that still needs people, output notices. In a captured one, it barely reacts. That response gap operationalizes gradual disempowerment.',
        view: 'shares',
        tick: 0,
        preset: 'defended',
      },
    ],
    engine: 'runEconomy',
    seed: 42,
    defaults: { ...ECONOMY_DEFAULTS },
    parameters: [
      range(
        'rho',
        'Substitution ρ',
        'How readily compute substitutes for labor.',
        'dynamics',
        -0.5,
        0.9,
        0.05
      ),
      range(
        'reinvestRate',
        'AI reinvestment',
        'Share of capital income reinvested each tick.',
        'dynamics',
        0,
        1,
        0.05
      ),
      range(
        'arrivalSpacing',
        'Arrival spacing',
        'Ticks between new AI systems entering.',
        'schedule',
        5,
        50,
        5,
        'ticks'
      ),
      range(
        'taxRate',
        'AI revenue tax',
        'Tax applied to compute-derived capital income.',
        'institutions',
        0,
        0.9,
        0.05
      ),
      range(
        'capShare',
        'Ownership cap',
        'Maximum share held by one active AI system.',
        'institutions',
        0.1,
        0.8,
        0.05
      ),
      toggle('aiTax', 'Revenue tax enabled', 'Redistributes capital income to households.'),
      toggle('ownershipCap', 'Ownership cap enabled', 'Constrains concentration among AI systems.'),
    ],
    presets: [
      {
        id: 'baseline',
        label: 'Undefended',
        note: 'AI capital arrives and compounds without intervention.',
        values: { aiTax: false, ownershipCap: false },
      },
      {
        id: 'tax',
        label: 'Revenue tax',
        note: 'Fiscal redistribution without ownership limits.',
        values: { aiTax: true, ownershipCap: false },
      },
      {
        id: 'defended',
        label: 'Tax + ownership cap',
        note: 'Two mechanisms act before reinvestment.',
        values: { aiTax: true, ownershipCap: true },
      },
    ],
    metrics: [
      { key: 'labor_share', label: 'Labor share', format: 'percent', better: 'higher' },
      { key: 'influence_now', label: 'Influence now', format: 'decimal', better: 'higher' },
      { key: 'human_income_share', label: 'Human income', format: 'percent', better: 'higher' },
      { key: 'income_gini', label: 'Income Gini', format: 'decimal', better: 'lower' },
    ],
    series: [
      { key: 'labor_share', label: 'Labor share', color: '#003b7e', max: 1 },
      { key: 'wage', label: 'Wage', color: '#4ab3f4' },
    ],
  },
  {
    id: 'cultural',
    index: '03',
    shortLabel: 'Culture',
    title: 'Cultural transmission',
    question: 'When does faster replication become displacement rather than exchange?',
    description:
      'Ideas spread over a friendship graph. Reproductive advantage and separation jointly determine the regime.',
    assumption:
      'Binary cultural lineage; complex contagion threshold; AI actors are permanent reservoirs.',
    evidence:
      'Paper example (16 seeds, T = 200): pluralism 0.79 / 0.12; assimilation 0.23 / 0.12; parallel cultures 0.98 / 0.93; displacement 0.25 / 0.93 (share / fault line).',
    modellingNotes: [
      'Culture is a binary lineage and AI actors are permanent reservoirs. Transmission advantage travels with the variant, while native reversion is an authored restoring force.',
      'The cultural floor is controlled by native reversion: reduce that rate to zero to test how much of the apparent stability was written into the model.',
      'Leaves out endogenous identity, strategic persuasion, new variants, memory, institutions of cultural production, and irreversible lock-in.',
    ],
    story: [
      {
        id: 'contagion',
        title: 'Culture you can catch',
        body: 'Forty agents share one friendship network. Eight AI agents are a permanent reservoir that never changes its mind. Everyone else catches cultural variants from friends and drifts back toward native culture when left alone.',
        view: 'system',
        tick: 3,
        preset: 'pluralism',
      },
      {
        id: 'pluralism',
        title: 'A fair fight is stable',
        body: 'AI is woven into the network and its ideas are exactly as transmissible as ours. Conversions and reversions balance, so the human-origin share stays high. This corner is pluralism: coexistence without takeover.',
        view: 'system',
        tick: 0,
        playTo: 180,
        speed: 2,
        preset: 'pluralism',
      },
      {
        id: 'assimilation',
        title: 'Make AI ideas six times catchier',
        body: 'The network is unchanged; one dial moves. AI-origin variants now spread six times more easily, and converted humans transmit them at full strength. The share collapses into one blended, increasingly AI-authored culture.',
        view: 'system',
        tick: 0,
        playTo: 180,
        speed: 2,
        preset: 'assimilation',
      },
      {
        id: 'parallel',
        title: 'Separate instead',
        body: 'Keep ideas equally transmissible but move AI into its own cluster. The graph’s primary fault line becomes the human–AI boundary. AI culture persists, but largely stays over there: parallel cultures.',
        view: 'faultline',
        tick: 0,
        playTo: 180,
        speed: 2,
        preset: 'parallel',
      },
      {
        id: 'displacement',
        title: 'Separate and catchier',
        body: 'Turn both dials up. The AI cluster keeps to itself, yet its more transmissible variants cross the few bridge friendships and spread through the human side. This is displacement: separation without protection.',
        view: 'faultline',
        tick: 0,
        playTo: 250,
        speed: 2,
        preset: 'displacement',
      },
      {
        id: 'two-measures',
        title: 'Why it takes two numbers',
        body: 'Assimilation and displacement can end with nearly the same cultural share. Only the pair — share and fault-line alignment — separates the four regimes. A single cultural score cannot tell those worlds apart.',
        view: 'system',
        tick: 0,
        preset: 'displacement',
      },
    ],
    engine: 'runCultural',
    seed: 60,
    defaults: { ...CULTURAL_DEFAULTS },
    parameters: [
      range(
        'aiHomophily',
        'AI separation',
        'Preference for within-type friendship edges.',
        'world',
        0,
        0.9,
        0.01
      ),
      range(
        'pAdvantage',
        'Replication advantage',
        'Relative transmissibility of AI-origin culture.',
        'dynamics',
        1,
        10,
        0.25,
        '×'
      ),
      range(
        'beta',
        'Base transmissibility',
        'Per-contact transmission strength.',
        'dynamics',
        0.01,
        0.12,
        0.005
      ),
      range(
        'recovery',
        'Native reversion',
        'Rate at which humans return to human-origin culture.',
        'dynamics',
        0,
        0.5,
        0.01
      ),
      range(
        'kThreshold',
        'Exposure threshold',
        'Independent exposures required for adoption.',
        'dynamics',
        1,
        3,
        1
      ),
    ],
    presets: [
      {
        id: 'pluralism',
        label: 'Pluralism',
        note: 'Integrated graph with equal replication.',
        values: { aiHomophily: 0.05, pAdvantage: 1 },
      },
      {
        id: 'assimilation',
        label: 'Assimilation',
        note: 'Integrated graph with faster AI-origin replication.',
        values: { aiHomophily: 0.05, pAdvantage: 6 },
      },
      {
        id: 'parallel',
        label: 'Parallel cultures',
        note: 'Separated graph with equal replication.',
        values: { aiHomophily: 0.9, pAdvantage: 1 },
      },
      {
        id: 'displacement',
        label: 'Displacement',
        note: 'Separation and replication advantage coincide.',
        values: { aiHomophily: 0.9, pAdvantage: 6 },
      },
    ],
    metrics: [
      {
        key: 'human_origin_share',
        label: 'Human-origin share',
        format: 'percent',
        better: 'context',
      },
      { key: 'fault_line', label: 'Fault-line alignment', format: 'decimal', better: 'context' },
      { key: 'cross_edges', label: 'Cross-type edges', format: 'integer', better: 'context' },
      { key: 'regime_code', label: 'Regime code', format: 'integer', better: 'context' },
    ],
    series: [
      { key: 'human_share', label: 'Human-origin share', color: '#003b7e', max: 1 },
      { key: 'conversions', label: 'Conversions', color: '#4ab3f4' },
    ],
  },
  {
    id: 'political',
    index: '04',
    shortLabel: 'Politics',
    title: 'Influence exchange',
    question: 'Who governs the consensus when attention rewires toward the already influential?',
    description:
      'Influence is the left eigenvector of a changing listening network. Amplification, sortition, and caps reshape it.',
    assumption: 'Anchored DeGroot learning; preferential attention; fixed AI opinion reservoir.',
    evidence:
      'Backend ladder (T = 400, 6 seeds): human share 0.87 organic / 0.54 amplified / 0.74 defended; influence equals the listening matrix’s left eigenvector (L1 error < 1e−3).',
    modellingNotes: [
      'Citizens use anchored DeGroot updates over one listening matrix. AI opinions remain fixed, and attention drifts preferentially toward current influence.',
      'The remaining human-influence floor is structural in this implementation; no exposed slider removes every anchoring and network constraint.',
      'Leaves out strategic messaging, coalition formation, platform adaptation, endogenous entry, persuasion content, and institutional lock-in.',
    ],
    story: [
      {
        id: 'constitution',
        title: 'Who listens to whom is the constitution',
        body: 'Thirty citizens and four AI actors share a listening network. Opinions pool along it, and each node’s eventual weight in the consensus is its influence. Attention drifts toward the already influential, so node size tracks power live.',
        view: 'system',
        tick: 0,
        playTo: 150,
        speed: 2,
        preset: 'organic',
      },
      {
        id: 'amplification',
        title: 'Amplification arrives',
        body: 'From tick 50, four AI actors receive algorithmic reach: every attention decision sees them as more attractive than their current influence warrants. Once they grow, preferential attachment continues the concentration.',
        view: 'system',
        tick: 30,
        playTo: 250,
        speed: 2,
        preset: 'amplified',
      },
      {
        id: 'consensus',
        title: 'The consensus drifts',
        body: 'The AI actors’ opinions are pinned away from truth. While influence is dispersed, noisy private signals average out. As amplification concentrates influence on that biased reservoir, consensus error rises without anyone being censored.',
        view: 'lorenz',
        tick: 100,
        playTo: 480,
        speed: 4,
        preset: 'amplified',
      },
      {
        id: 'attention-defense',
        title: 'Defend the attention structure itself',
        body: 'Sortition periodically returns part of every citizen’s listening to a civic lottery. An influence cap dampens the attractiveness of nodes above the limit. Both defenses change attention itself, not merely the resulting opinion.',
        view: 'system',
        tick: 0,
        playTo: 250,
        speed: 2,
        preset: 'defended',
      },
      {
        id: 'political-explore',
        title: 'Over to you',
        body: 'Try amplification, drift, susceptibility, and the sortition cadence. The human-influence curve is the quantity to watch; consensus alone cannot tell you whose attention structure produced it.',
        view: 'lorenz',
        tick: 0,
        preset: 'defended',
      },
    ],
    engine: 'runPolitical',
    seed: 7,
    defaults: { ...POLITICAL_DEFAULTS },
    parameters: [
      range(
        'amplification',
        'AI amplification',
        'Extra attractiveness applied after the onset tick.',
        'dynamics',
        1,
        8,
        0.5,
        '×'
      ),
      range(
        'updateRate',
        'Attention drift',
        'How quickly listening follows current influence.',
        'dynamics',
        0,
        0.2,
        0.01
      ),
      range(
        'susceptibility',
        'Susceptibility λ',
        'Weight placed on neighbors versus private signal.',
        'dynamics',
        0.3,
        0.95,
        0.05
      ),
      range(
        'sortitionCadence',
        'Sortition cadence',
        'Ticks between civic rebalancing events.',
        'schedule',
        5,
        50,
        5,
        'ticks'
      ),
      range(
        'capShare',
        'Influence cap',
        'Share above which attraction is damped.',
        'institutions',
        0.03,
        0.15,
        0.01
      ),
      toggle('sortition', 'Sortition', 'Returns part of citizen attention to a civic lottery.'),
      toggle('influenceCap', 'Influence cap', 'Stops over-cap nodes attracting new attention.'),
    ],
    presets: [
      {
        id: 'organic',
        label: 'Organic',
        note: 'No algorithmic amplification.',
        values: { ampOnset: 9999, sortition: false, influenceCap: false },
      },
      {
        id: 'amplified',
        label: 'Amplified',
        note: 'Amplification begins at tick 50.',
        values: { ampOnset: 50, sortition: false, influenceCap: false },
      },
      {
        id: 'defended',
        label: 'Sortition + cap',
        note: 'Institutional defenses alter attention itself.',
        values: { ampOnset: 50, sortition: true, influenceCap: true },
      },
    ],
    metrics: [
      {
        key: 'human_influence_share',
        label: 'Human influence',
        format: 'percent',
        better: 'higher',
      },
      { key: 'influence_gini', label: 'Influence Gini', format: 'decimal', better: 'lower' },
      { key: 'consensus_error', label: 'Consensus error', format: 'decimal', better: 'lower' },
      { key: 'top_share', label: 'Top actor share', format: 'percent', better: 'lower' },
    ],
    series: [
      { key: 'human_share', label: 'Human influence', color: '#003b7e', max: 1 },
      { key: 'consensus_error', label: 'Consensus error', color: '#4ab3f4' },
    ],
  },
  {
    id: 'combined',
    index: '05',
    shortLabel: 'Coupled',
    title: 'The coupled society',
    question:
      'Do defenses that work alone survive when money, culture, and political power form a loop?',
    description:
      'The same population participates in three domains. Coupling closes the economic → cultural → political → economic flywheel.',
    assumption:
      'One shared population; interleaved domain clocks; three explicit cross-domain transforms.',
    evidence:
      'Backend ladder (T = 500, 8 seeds): human income share 0.12 → 0.07 undefended when coupled; composite 0.76 sealed-defended / 0.63 coupled-defended; transfer gap 0.128 defended > 0.109 undefended; correlated decline −0.02 → 0.60.',
    modellingNotes: [
      'The floor is itemized: culture stops near 0.59 because of native reversion; set it to zero on the cultural scenario and the floor is nearly gone (0.008). Politics stops near 0.46 for structural reasons. The economy has no floor and is still sliding at tick 1500. “The system does not fully collapse” is partly an assumption, not a finding.',
      'Composition, not a new model: the other three scenarios’ equations run interleaved over one population. Their assumptions and floors are inherited.',
      'Five couplings share one coupling κ control: money buys reach, culture directs attention, influence writes the rules, captured rules pay rents to AI capital, and converted humans buy AI services. Every channel is exactly neutral at κ = 0, giving each run a sealed, same-seed twin.',
      'Coupling gains are hand-set and linear, chosen for legibility. Their magnitudes determine the scale of the result; only sign and ordering claims are treated as robust across cadence and defense sweeps.',
      'Per-domain defaults are deliberately mild so joint decline can be attributed to coupling rather than three separately lethal baselines.',
      'Undefended, politics is a sink: without a tax to erode, influence loss has no downstream enforcement consequence.',
      'Leaves out additional arrows and irreversibility. This is a loop plus two rent channels, not the paper’s full mesh; every quantity is a rate or level rather than a basin. Mid-collapse rescue and spectral lock-in remain unverified research work, not findings.',
    ],
    story: [
      {
        id: 'sealed',
        title: 'Three systems, one population, sealed',
        body: 'The same people supply labor, hold culture, and grant attention; the same AI actors accumulate capital, broadcast, and attract influence. With coupling at zero, the three domains are sealed. Defended, each can hold.',
        view: 'system',
        tick: 0,
        playTo: 200,
        speed: 4,
        preset: 'sealed',
      },
      {
        id: 'coupled',
        title: 'Now couple them — the loop closes',
        body: 'Money buys reach, cultural conversion directs attention, and political influence weakens the rules governing capital. That influence deficit feeds rent back into AI capital, where reinvestment compounds it. The final return arrow makes a flywheel rather than a cascade.',
        view: 'system',
        tick: 0,
        playTo: 300,
        speed: 4,
        preset: 'transfer',
      },
      {
        id: 'gap',
        title: 'The defense transfer gap',
        body: 'This run is compared with its sealed twin: the same seed and defenses, with coupling set to zero. The transfer gap is the protection lost when individually successful defenses enter the coupled world.',
        view: 'system',
        tick: 300,
        playTo: 480,
        speed: 4,
        preset: 'transfer',
      },
      {
        id: 'undefended',
        title: 'Undefended and coupled',
        body: 'Remove the tax, sortition, and cap while keeping coupling high. Each domain would describe its own slide as gradual; correlated decline reveals the shared flywheel.',
        view: 'system',
        tick: 0,
        playTo: 250,
        speed: 4,
        preset: 'undefended',
      },
      {
        id: 'coupled-explore',
        title: 'Over to you',
        body: 'Composition, not a new model, is the experiment. Move coupling and watch whether defenses that pass every single-domain benchmark survive the joined system. The pipeline view exposes all three cross-domain transforms.',
        view: 'system',
        tick: 0,
        preset: 'transfer',
      },
    ],
    engine: 'runCombined',
    seed: 34,
    defaults: { ...COMBINED_DEFAULTS, aiTax: true, sortition: true, influenceCap: true },
    parameters: [
      range(
        'kappa',
        'Coupling κ',
        'Strength of all cross-domain channels.',
        'dynamics',
        0,
        1,
        0.05
      ),
      range(
        'amplification',
        'AI amplification',
        'Base political reach advantage.',
        'dynamics',
        1,
        6,
        0.5,
        '×'
      ),
      range(
        'pAdvantage',
        'Cultural advantage',
        'Base replication advantage before economic coupling.',
        'dynamics',
        1,
        6,
        0.25,
        '×'
      ),
      range(
        'reinvestRate',
        'AI reinvestment',
        'Capital-income compounding rate.',
        'dynamics',
        0,
        1,
        0.05
      ),
      range(
        'captureGain',
        'Rule capture',
        'Rent extraction created by lost political enforcement.',
        'dynamics',
        0,
        1,
        0.05
      ),
      range('econCadence', 'Economy clock', 'Ticks between economic updates.', 'schedule', 1, 6, 1),
      range(
        'cultureCadence',
        'Culture clock',
        'Ticks between cultural updates.',
        'schedule',
        1,
        6,
        1
      ),
      range(
        'politicsCadence',
        'Politics clock',
        'Ticks between political updates.',
        'schedule',
        1,
        6,
        1
      ),
      toggle('aiTax', 'AI revenue tax', 'An enforcement-scaled economic defense.'),
      toggle('sortition', 'Sortition', 'A periodic political defense.'),
      toggle('influenceCap', 'Influence cap', 'A structural political defense.'),
    ],
    presets: [
      {
        id: 'sealed',
        label: 'Sealed + defended',
        note: 'The same defenses with κ = 0.',
        values: { kappa: 0, aiTax: true, sortition: true, influenceCap: true },
      },
      {
        id: 'transfer',
        label: 'Coupled + defended',
        note: 'The flagship defense-transfer condition.',
        values: { kappa: 0.8, aiTax: true, sortition: true, influenceCap: true },
      },
      {
        id: 'undefended',
        label: 'Coupled + undefended',
        note: 'The flywheel without institutional defenses.',
        values: { kappa: 0.8, aiTax: false, sortition: false, influenceCap: false },
      },
    ],
    metrics: [
      { key: 'transfer_gap', label: 'Transfer gap', format: 'points', better: 'lower' },
      { key: 'composite', label: 'Composite share', format: 'percent', better: 'higher' },
      { key: 'human_income_share', label: 'Human income', format: 'percent', better: 'higher' },
      {
        key: 'correlated_decline',
        label: 'Correlated decline',
        format: 'decimal',
        better: 'lower',
      },
    ],
    series: [
      { key: 'income_share', label: 'Economy', color: '#003b7e', max: 1 },
      { key: 'culture_share', label: 'Culture', color: '#4ab3f4', max: 1 },
      { key: 'influence_share', label: 'Politics', color: '#89cff0', max: 1 },
    ],
  },
];

export const scenarioById = Object.fromEntries(
  scenarios.map((scenario) => [scenario.id, scenario])
) as Record<ScenarioId, ScenarioDefinition>;
