// config/docs.config.js
// Documentation and sidebars configuration

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 * 
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 * Create as many sidebars as you want.
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Manual sidebar configuration (for future use)
  /*
  researchSidebar: [
    'research/intro',
    {
      type: 'category',
      label: 'Research Areas',
      items: [
        'research/collective-intelligence',
        'research/ai-safety',
        'research/complex-systems',
      ],
    },
  ],
  
  projectsSidebar: [
    'projects/overview',
    {
      type: 'category',
      label: 'Active Projects',
      items: [
        'projects/simulation-framework',
        'projects/coordination-protocols',
      ],
    },
  ],
  */
};

// Docs configuration
const docsConfig = {
  // Main docs configuration
  docs: {
    sidebarPath: require.resolve('../config/docs.config.js'),
    editUrl: 'https://github.com/Equilibria-Network/eq-network/tree/main/',
    showLastUpdateAuthor: true,
    showLastUpdateTime: true,
    
    // Breadcrumbs
    breadcrumbs: true,
    
    // Tags
    tags: 'tags.yml',
    
    // Versioning (for future use)
    // versions: {
    //   current: {
    //     label: 'Next 🚧',
    //     path: 'next',
    //   },
    // },
  },
  
  // Sidebars configuration
  sidebars,
};

module.exports = docsConfig;
